const fs = require("fs");
const file = "backend/controllers/user.controller.js";
let content = fs.readFileSync(file, "utf8");
content = content.replace('select: "fullName profilePic",', 'select: "fullName profilePic username",');
content = content.replace('participantId: otherParticipant._id', 'participantId: otherParticipant._id,\n                        username: otherParticipant.username');
content = content.replace('export const getUserById = async (req, res) => {', 'export const getUserByUsername = async (req, res) => {');
content = content.replace('const { id } = req.params;', 'const { username } = req.params;');
content = content.replace('const user = await User.findById(id).select("-password");', 'const user = await User.findOne({ username }).select("-password");');
content = content.replace('console.error("Error in getUserById: ", error.message);', 'console.error("Error in getUserByUsername: ", error.message);');
fs.writeFileSync(file, content);
